[package]
name = "strata-lighting"
version.workspace = true
edition.workspace = true

[dependencies]
strata-core = { path = "../core" }
strata-ecs = { path = "../ecs" }
bevy_ecs.workspace = true
bevy_app.workspace = true
glam.workspace = true
tracing.workspace = true

[[bench]]
name = "lighting_bench"
harness = false

[dev-dependencies]
divan.workspace = true