[workspace]
resolver = "2"
members = [
    "crates/strata_core",
    "crates/strata_world",
    "crates/strata_physics",
    "crates/strata_render",
    "crates/strata_player",
    "bin/client",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kilo-Org/strata"

[workspace.dependencies]
bevy = { version = "0.18", default-features = false }
bevy_rapier3d = { version = "0.34", default-features = false, features = [
    "enhanced-determinism",
    "dim3",
] }

[profile.dev]
opt-level = 1
debug = 1
split-debuginfo = "unpacked"
incremental = true
codegen-units = 256
lto = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
