[package]
name = "strata-storage"
version.workspace = true
edition.workspace = true

[dependencies]
strata-core = { path = "../core" }
glam.workspace = true
rkyv.workspace = true
zstd.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true
hashbrown.workspace = true
fjall.workspace = true

[[bench]]
name = "storage_bench"
harness = false

[dev-dependencies]
divan.workspace = true
dhat.workspace = true
tempfile = "3.8"

