//! M5 world-generation tests: determinism, round-trip, boundary, plugin chain.

use std::sync::Arc;

use bevy::prelude::*;

use strata_core::prelude::*;
use strata_core::registry::load_block_registry;

use crate::generator::{generate_compressed, generate_sector};
use crate::plugin::{Generated, WorldGenPlugin};

/// Byte-stable signature of a [`CompressedChunkData`] for equality checks
/// (the struct does not derive `PartialEq`, so we compare field-by-field).
fn chunk_signature(c: &CompressedChunkData) -> Vec<u8> {
    let mut out = Vec::new();
    for v in c.coord.iter() {
        out.extend_from_slice(&v.to_le_bytes());
    }
    out.extend_from_slice(&c.sector_mask.to_le_bytes());
    for id in &c.palette {
        out.extend_from_slice(&id.0.to_le_bytes());
    }
    for b in &c.bricks {
        out.push(b.brick_idx);
        out.extend_from_slice(&b.sub_mask.to_le_bytes());
        for sub in &b.subs {
            out.push(sub.voxel_mask);
            for idx in &sub.indices {
                out.push(*idx);
            }
        }
    }
    out
}

fn count_solid(pool: &GlobalBrickPool, map: &XBrickMap) -> usize {
    let mut n = 0;
    for lx in 0..32u32 {
        for ly in 0..32u32 {
            for lz in 0..32u32 {
                if map.is_occupied(pool, VoxelCoord::new(lx, ly, lz)) {
                    n += 1;
                }
            }
        }
    }
    n
}

#[test]
fn determinism_same_seed_and_coord_is_byte_identical() {
    let reg = load_block_registry();
    let a = generate_compressed(SectorCoord(2, -1, 5), &reg);
    let b = generate_compressed(SectorCoord(2, -1, 5), &reg);
    assert_eq!(chunk_signature(&a), chunk_signature(&b));
}

#[test]
fn determinism_different_coords_differ() {
    let reg = load_block_registry();
    let a = generate_compressed(SectorCoord(0, 0, 0), &reg);
    let b = generate_compressed(SectorCoord(1, 0, 0), &reg);
    assert_ne!(chunk_signature(&a), chunk_signature(&b));
}

#[test]
fn round_trip_pack_unpack_equal_per_voxel() {
    let reg = load_block_registry();
    let mut pool = GlobalBrickPool::new();
    let mut palette = SectorPalette::new();
    let map = generate_sector(SectorCoord(3, 0, -2), &reg, &mut pool, &mut palette);

    let data = map.pack(&pool, &palette);
    let mut pool2 = GlobalBrickPool::new();
    let (map2, palette2) = data.unpack(&mut pool2);

    for lx in 0..32u32 {
        for ly in 0..32u32 {
            for lz in 0..32u32 {
                let c = VoxelCoord::new(lx, ly, lz);
                assert_eq!(
                    map.get_block(&pool, &palette, c),
                    map2.get_block(&pool2, &palette2, c),
                    "voxel mismatch at ({lx},{ly},{lz})"
                );
            }
        }
    }
}

#[test]
fn boundary_y0_is_bedrock_full_solid() {
    let reg = load_block_registry();
    let mut pool = GlobalBrickPool::new();
    let mut palette = SectorPalette::new();
    let map = generate_sector(SectorCoord(0, 0, 0), &reg, &mut pool, &mut palette);

    let mut solid = 0;
    for lx in 0..32u32 {
        for lz in 0..32u32 {
            if map.is_occupied(&pool, VoxelCoord::new(lx, 0, lz)) {
                solid += 1;
            }
        }
    }
    assert_eq!(solid, 32 * 32, "y==0 layer must be fully solid bedrock");
}

#[test]
fn boundary_high_sector_top_is_sky() {
    let reg = load_block_registry();
    let mut pool = GlobalBrickPool::new();
    let mut palette = SectorPalette::new();
    // Sector well above any terrain (world Y 320..351).
    let map = generate_sector(SectorCoord(0, 10, 0), &reg, &mut pool, &mut palette);

    let mut solid_top = 0;
    for lx in 0..32u32 {
        for lz in 0..32u32 {
            if map.is_occupied(&pool, VoxelCoord::new(lx, 31, lz)) {
                solid_top += 1;
            }
        }
    }
    // The entire top layer should be air (sky) for a high sector.
    assert!(
        solid_top == 0,
        "top layer of a high sector must be air, found {solid_top} solid"
    );
}

#[test]
fn generates_non_trivial_terrain() {
    let reg = load_block_registry();
    let mut pool = GlobalBrickPool::new();
    let mut palette = SectorPalette::new();
    let map = generate_sector(SectorCoord(0, 0, 0), &reg, &mut pool, &mut palette);
    let solid = count_solid(&pool, &map);
    assert!(solid > 1000, "expected substantial terrain, got {solid}");
}

/// End-to-end ECS chain: a sector entity is generated by `WorldGenPlugin`
/// (async compute) and receives its `XBrickMap` + `Generated` marker.
#[test]
fn plugin_generates_sector_entity() {
    let mut app = App::new();
    app.insert_resource(load_block_registry());
    app.insert_resource(GlobalBrickPool::new());
    app.add_strata_plugin(WorldGenPlugin);
    let e = app.world_mut().spawn(SectorCoord(0, 0, 0)).id();

    // Run enough frames for the async compute task to complete + apply.
    for _ in 0..40 {
        app.update();
    }

    let entity = app.world().entity(e);
    assert!(
        entity.contains::<Generated>(),
        "sector must be marked Generated"
    );
    assert!(
        entity.contains::<XBrickMap>(),
        "sector must have an XBrickMap component"
    );
}

#[test]
fn plugin_generated_sector_is_solid_at_bedrock() {
    let mut app = App::new();
    app.insert_resource(load_block_registry());
    app.insert_resource(GlobalBrickPool::new());
    app.add_strata_plugin(WorldGenPlugin);
    let e = app.world_mut().spawn(SectorCoord(0, 0, 0)).id();
    for _ in 0..40 {
        app.update();
    }

    let world = app.world();
    let entity = world.entity(e);
    let map = entity.get::<XBrickMap>().expect("XBrickMap present");
    let pool = world.resource::<GlobalBrickPool>();
    let mut solid = 0;
    for lx in 0..32u32 {
        for lz in 0..32u32 {
            if map.is_occupied(pool, VoxelCoord::new(lx, 0, lz)) {
                solid += 1;
            }
        }
    }
    assert_eq!(solid, 32 * 32, "generated sector must have solid bedrock");
}

#[test]
fn compressed_is_arc_shareable() {
    let reg = load_block_registry();
    let a: Arc<CompressedChunkData> = generate_compressed(SectorCoord(5, 0, 5), &reg);
    let b = a.clone();
    assert_eq!(chunk_signature(&a), chunk_signature(&b));
}
