//! Core voxel pipeline ordering sets (prototype skeleton).
//!
//! Enforces `Streaming -> Input -> WorldGen -> Meshing -> Physics -> Lighting
//! -> RenderUpdate`. Streaming runs first so freshly spawned sector entities are
//! generated by `WorldGen` in the same frame.

use bevy::prelude::*;

/// Core scheduling sets for the single-player prototype pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, SystemSet)]
pub enum StrataSet {
    /// Sector load/unload around the player (M9). Runs before `WorldGen` so the
    /// newly spawned sector entities are generated in the same frame.
    Streaming,
    /// Input sampling + write-back from SubApps.
    Input,
    /// Generate sector data.
    WorldGen,
    /// Build mesh (async apply).
    Meshing,
    /// Physics step.
    Physics,
    /// L0/L1 lighting.
    Lighting,
    /// Upload to GPU.
    RenderUpdate,
}
