[package]
name = "strata-fluid"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
strata-core = { path = "../core" }
strata-ecs = { path = "../ecs" }
bevy_ecs.workspace = true
bevy_app.workspace = true
bevy_time.workspace = true
hashbrown.workspace = true
glam.workspace = true
