[package]
name = "strata-inventory"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
strata-ecs = { path = "../ecs" }
strata-entity = { path = "../entity" }
bevy_ecs.workspace = true
bevy_app.workspace = true
bevy_math.workspace = true
bevy_transform.workspace = true
bevy_input.workspace = true
bevy_window.workspace = true
bevy_rapier3d.workspace = true
glam.workspace = true
serde = { workspace = true, features = ["derive"] }
